### ISSUE TITLE
UPS: Gibberish tracking ID crashes app

### ISSUE THREAD

**Issue by PhilippKosarev** [itsvic-dev/parcel#39]
Adding a parcel with some gibberish crashes the app, sometimes, and sometimes it doesn't. Not sure what the pattern is here.

![Image](https://github.com/user-attachments/assets/4fbd2ab9-da5f-41fe-9482-50231473ec68)

Crash log from trying to open the parcel entry:
```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: dev.itsvic.parceltracker, PID: 12031
G0.e: Non-null value 'progressBarType' was null at $.trackDetails[0].progressBarType
	at M2.e.j(Unknown Source:63)
	at dev.itsvic.parceltracker.api.UPSDeliveryService_TrackDetailsJsonAdapter.a(Unknown Source:116)
	at M2.a.a(Unknown Source:15)
	at L2.h.a(Unknown Source:47)
	at M2.a.a(Unknown Source:15)
	at dev.itsvic.parceltracker.api.UPSDeliveryService_GetStatusResponseJsonAdapter.a(Unknown Source:31)
	at M2.a.a(Unknown Source:15)
	at d4.c.h(Unknown Source:31)
	at c4.A.e(Unknown Source:57)
	at o2.c.d(Unknown Source:8)
	at N3.m.run(Unknown Source:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: y3.e: [C0.I0@b4867ce, Q.g@4c926ef, i0{Cancelling}@f5c95fc, f0@d06d485]
```

**Comment by itsvic-dev** [comment]
it appears that this issue is relevant to the UPS backend only
i pushed a fix into the parcel archival branch, which should land in master soon

**Comment by PhilippKosarev** [comment]
Seems like it's still crashing in 1.1.0, but with a different error

```
FATAL EXCEPTION: DefaultDispatcher-worker-4
Process: dev.itsvic.parceltracker, PID: 8103
G0.e: Non-null value 'trackDetails' was null at $.trackDetails
	at M2.e.j(Unknown Source:63)
	at dev.itsvic.parceltracker.api.UPSDeliveryService_GetStatusResponseJsonAdapter.a(Unknown Source:40)
	at M2.a.a(Unknown Source:15)
	at d4.c.h(Unknown Source:31)
	at c4.A.e(Unknown Source:57)
	at o2.c.d(Unknown Source:8)
	at N3.m.run(Unknown Source:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: y3.e: [C0.I0@c50512b, Q.g@92fd988, i0{Cancelling}@4d73f21, f0@9681f46]
```
